menu:
- {name: 'CURRICULUM VITAE', url: '/cv'}

contact:
- {name: 'CONTACT', url: '/contact'}

social:
- {icon: 'envelope', link: 'mailto:epoch1026 [at] kaist [dot] ac [dot] kr'}

contacts:
- {name: 'YeongHyeon Na', title: 'Undergraduate Student (Freshman)', school: 'Korea Advanced Institute of Science and Technology', number: 'Class of 2029', email: 'epoch1026@kaist.ac.kr''}
