menu:
- {name: 'CURRICULUM VITAE', url: '/cv'}
- {name: 'COURSEWORK', url: '/coursework-field'}

contact:
- {name: 'CONTACT', url: '/contact'}

social:
- {icon: 'envelope', link: 'mailto:epoch1026 [at] kaist [dot] ac [dot] kr'}
- {icon: 'orcid', link: 'https://orcid.org/0009-0004-3464-6499'}

contacts:
- {name: 'YeongHyeon NA', title: 'Undergraduate Student (Electrical Engineering)', school: 'Korea Advanced Institute of Science and Technology', number: 'Class of 2029', email: 'epoch1026 [at] kaist [dot] ac [dot] kr', linkedin: 'ynghyn-na', orcid: '0009-0004-3464-6499'}

#성과와 문서화가 안된 것들
projects:
- {name: 'Projects', url: '/projects'}

#문서화되고 지도받은 오랜기간 한것
research:
- {name: 'Research', url: '/research'}
